### ISSUE TITLE
Handle Java Reserved Words/Keywords

### ISSUE THREAD

**Issue by adjokic** [mulesoft-labs/raml-for-jax-rs#234]
Hi,
I am trying to find a way to deal with Java reserved words in the raml -> jax-rs generation.
This happens when I have a raml data type with, for example:
```
#%RAML 1.0 DataType
properties:
  supportedProperty:
    type: string
  class:
    type: string
```
this will fail with the following error during raml generation:
`[ERROR] Failed to execute goal org.raml:raml-to-jaxrs-maven-plugin:2.0.0-RC2-SNAPSHOT:generate (default-cli) on project raml: Error generating Java classes from: null: not a valid name: class -> [Help 1]`

Any ideas how to deal with this the best way? A couple of things:
- I need to generate a JSON object from this generated PoJo, so ideally I would like to keep the property name in the RAML untouched
- I am OK with changing the names of Java classes/fields/methods, so this would have to be dealt with in the generator.

Thanks
