### ISSUE TITLE
Form parameters support

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#280]
Are form parameters supported using RAML 1.0 from RAML to Java?

For example
```
/foo:
  post:
    body:
      application/x-www-form-urlencoded:
        type:
          properties:
            bar:
              type: string
```
