### ISSUE TITLE
Bad code generation with optional nil values

### ISSUE THREAD

**Issue by Maxim-Chernyavsky** [mulesoft-labs/raml-for-jax-rs#293]
Got a problem generating code with raml-to-jaxrs-cli when raml contains unions with nil values. Here is an example from specification

```
#%RAML 1.0
title: test nil values
types:
  NilValue:
    type: object
    properties:
      name:
      comment: nil | string
```

`$ java -jar ./raml-to-jaxrs-cli-2.1.0-jar-with-dependencies.jar  -d /tmp -r org.tst /tmp/NilValue.raml  
`

I receive two classes

$ cat /tmp/org/tst/NilValue.java 
```
package org.tst;

import java.lang.String;

public interface NilValue {
  String getName();

  void setName(String name);

  Comment getComment();

  void setComment(Comment comment);
}
```

$ cat /tmp/org/tst/NilValueImpl.java 

```
package org.tst;

import java.lang.String;

public class NilValueImpl implements NilValue {
  private String name;

  private Comment comment;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Comment getComment() {
    return this.comment;
  }

  public void setComment(Comment comment) {
    this.comment = comment;
  }
}
```

None of these files contains the declaration of Comment class.
