### ISSUE TITLE
java.time APIs and RAML Types

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#294]
Is there a way to use java.time APIs (e.g. LocalDateTime, LocalDate and LocalTime, ecc.) with RAML Types like datetime, date-only, time-only, ecc.?

**Comment by chrisjamesconnor** [comment]
Hi - wondered if there was any answer to this? Other than doing some JavaPoet type work on our own ?

**Comment by jpbelang** [comment]
Right now, it's java poet stuff.  Which is a bit of a pain.

However, i'm working on a raml-to-pojo (which would be used by ramlforjaxrs) that would swap them out wholesale.

**Comment by chrisjamesconnor** [comment]
Excellent - I am currently working on specifying an approach for our applications. Would I be better waiting on this to bottom out (ie for you to finish this work).

I am currently using annotationTypes to map className properties so that we generate java.time.Local date (creating a ramltojaxrs.raml) file in the process.

This seems to work well for our use cases at this early stage. We are also using a similar technique to generate Lombok builder annotations (using your @depricated example as inspiration!). This allows us to generate builders on our generates Impl classes which is very useful with the layers of our apps.

Will this be maintained moving forward? Do you have another view regarding this approach?

**Comment by jpbelang** [comment]
Ooooooh.  Lombok.  That's a great idea.  Unfortunately, the RAML type have changed the way of writing plugins a bit.

As to changing the type, you can now (in release/2.2.0) change the type being used.  You could check out this annotation:
```yaml
#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
mediaType: application/json
uses:
  ramltopojo: ramltopojo.raml
/search:
    description: The search resource
    uriParameters:
        id:
            type: date
            (ramltopojo.types):
              plugins:
                - name: core.changeType
                  arguments: [ java.time.LocalDate ]
```
