### ISSUE TITLE
minimum, maximum validations on integer are not populated.

### ISSUE THREAD

**Issue by SwathiYakkali** [mulesoft-labs/raml-for-jax-rs#306]
I have raml configuration as below:
 ```
  types:
     Weight:
       type: integer
       minimum: 3
       maximum: 5
```

In the generated Java class, there are no validations set at the `Weight` property.
