### ISSUE TITLE
Support for "inline" multiple inheritance

### ISSUE THREAD

**Issue by DavideRossi** [mulesoft-labs/raml-for-jax-rs#318]
```
types:
  A:
  B:
  C:
    type: [A, B]

/foo:
  post:
    body:
      type: [A, B]
```
is not supported (I'm guessing since it produces erroneous code) whereas
```
    body:
      type C
```
is.

Maybe this is a duplicate of #245?
