### ISSUE TITLE
Generated types with raml-to-jaxrs maven plugin

### ISSUE THREAD

**Issue by amagnus** [mulesoft-labs/raml-for-jax-rs#321]
Assuming I have the following RAML type:

```
Person:
  properties:
    name: string
    age: number
```

Running the maven plugin does generate a Person interface, as well as a PersonImpl class. However I think we only need the implementation in most cases, and the two files are generated anyway.

How about adding a config flag to skip generating the DTO interfaces?
