### ISSUE TITLE
RAML containing multipart form data does not generate compileable code

### ISSUE THREAD

**Issue by cpkr** [mulesoft-labs/raml-for-jax-rs#334]
We created a raml file containing a post request with mulitpart formdata. The fragment used is equivalent to the one in file jaxrs-to-raml-examples/jaxrs-to-raml-maven-examples/jaxrs-to-raml-multipart/target/generated-sources/raml-jaxrs/jaxrs-to-raml-multipart.raml from the currrent Snapshot:

```
/theMultiparts:
    post:
        body:
            multipart/form-data:
                type:
                    properties:
                        appBundle:
                            type: file
```

When generating the java code via maven the resource does contain a class for this parameter which had not been generated
I copied the file from the git repo to my project and generated the class. The same problem does occur. Following is generated for the post method:
```
  @POST
  @Consumes("multipart/form-data")
  PostTheMultipartsResponse postTheMultiparts(TheMultipartsPostMultipartFormData entity);

```

**Comment by jpbelang** [comment]
is this on master ?  Just to be clear the "TheMultipartsPostMultipartFormData" is not generated ?

**Comment by jpbelang** [comment]
I've built a plugin to handle this case.  The reason I've built a plugin is that form data implementation are server specific (I may be wrong, but all examples I've seen seem to indicate this).

Look at the torture test for usage.  Tell me if I missed something.

**Comment by cpkr** [comment]
Thanks for the update. Unfortunately the branch release/3.0.0 does not compile to me:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project raml-defined-example: Compilation failure: Compilation failure: 
[ERROR] /data/projects/dcep/git/raml-for-jax-rs/raml-to-jaxrs/examples/maven-examples/raml-defined-example/target/generated-sources/raml-to-jaxrs-maven-plugin/example/support/LimbDeserializer.java:[32,37] example.model.Limb is abstract; cannot be instantiated

**Comment by jpbelang** [comment]
Are you sure you are up to date ? The travis-ci build is passing.  

https://travis-ci.org/mulesoft-labs/raml-for-jax-rs

**Comment by cpkr** [comment]
Looks fine from the generated code. I will continue with the implementation and reply if also this part works.

Thanks for your support.

**Comment by cpkr** [comment]
I found one issue in new implementation: If you have a uri parameter this is not generated as parameter.
Example:
```
/theMultiparts:
    /{uident}:
        description: File upload
        uriParameters:
            uident:
                description: uident - Uuid of the form
                type: string
        post:
            body:
                multipart/form-data:
                    type: object
                    properties:
                        appBundle:
                            type:
                                type: file
                                displayName:
                                    value: type
                            displayName:
                                value: appBundle
                    displayName:
                        value: "multipart/form-data"
```

Do you also have a solution for this one?
