### ISSUE TITLE
Pattern properties

### ISSUE THREAD

**Issue by oliverdozsa** [mulesoft-labs/raml-for-jax-rs#345]
Hello,

Are pattern properties supported?
When I try to generate from this RAML (it's from the spec):
```
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
```

I get:

```
Error generating Java classes from: null: not a valid name:
```
