### ISSUE TITLE
JSR 303 - @valid annotation is not getting generated on the List of complex type

### ISSUE THREAD

**Issue by gr423** [mulesoft-labs/raml-for-jax-rs#361]
Hi Team ,

I've the below RAML

```
event:
type: object
properties:
  metadataset:
   required: false
   type: metadatSetType[]

metadatSetType:
  type: object
  properties:
    locale:
    required: true
    type: string
  name:
    required:false
    type: string
```

Generated Java Objects  are as below ,

I'm expecting the @valid annotation on the metadataSet of event .Which is not getting generated.
And the JsonMapperConfiguration is never considered while generating the code .
includeAdditionalproperties is made false , but still the java objects generated has the field.

```
@JsonInclude(JsonInclude.Include.NON_NULL)
Class Event
{
    @JsonProperty("metadataSet")
    List<MetadatSetType> metadataSet;
  @JsonIgnore
  private Map<String, Object> additionalProperties = new HashMap<String, Object>();
}

```
```
@JsonInclude(JsonInclude.Include.NON_NULL)
Class MetadatasetType
{
 @JsonProperty("locale")
 @NotNull
  String locale;
 @JsonProperty("name")
String name;
  @JsonIgnore
  private Map<String, Object> additionalProperties = new HashMap<String, Object>();
}
```
Pom File 
```

<plugin>
<groupId>org.raml.jaxrs</groupId>
<artifactId>raml-to-jaxrs-maven-plugin</artifactId>
<version>3.0.1</version>
<executions>
<execution>
<id>GenerateAdminV2</id>
<goals>
<goal>generate</goal>
</goals>
<phase>generate-sources</phase>
<configuration>
<ramlFile>${basedir}/src/main/resources/raml/v1/MAS_api.raml</ramlFile>
<resourcePackage>com..mas.v1.resource</resourcePackage>
<modelPackage>com..mas.v1.model</modelPackage>
<removeOldOutput>true</removeOldOutput>
<generateTypesWith>
	<value>jsr303</value>
	<value>jackson2</value>
   </generateTypesWith>
  <jsonMapperConfiguration>
	 <includeAdditionalProperties>false</includeAdditionalProperties>
</jsonMapperConfiguration>
</configuration>
</execution>
</executions>
</plugin>

```
