### ISSUE TITLE
Primitive type byte array (byte[])

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#384]
I'd like to define a byte[] property (the serialization/deserialization is managed by an extension I wrote).

The only results I obtained are the following ones.

Giving
```
  X:
    (ramltopojo.types):
      plugins:
        - name: core.changeType
          arguments: [ java.lang.Byte, unbox ]
    type: string
```

this piece or RAML

```
  Y:
    properties:
      prop:
        type: X
```

produces 
```
byte prop
```

while

```
  Y:
    properties:
      prop:
        type: X[]
```
produces

```
List<Byte> prop
```

What I'd need is
```
byte[] prop
```

Is there a way to achieve it?
