### ISSUE TITLE
Can we have the Java Wrapper type generated for boolean RAML type.

### ISSUE THREAD

**Issue by gr423** [mulesoft-labs/raml-for-jax-rs#386]
We have the boolean element  . When its not present in the request payload , by default it takes the value  "false" , which would override the value .
Is there a way to generate the wrapper type , so we ignore the null fields .

Thanks 
Ramya

**Comment by jpbelang** [comment]
Plugins!

The core.box plugin will box primitive types. You could activate it on any property 
```yaml
uses:
  ramltopojo: ramltopojo.raml
types:
  TradeProperties:
    additionalProperties: false
    properties:
      fromCount: integer
        (ramltopojo.types):
          plugins:
            - core.core
```
