### ISSUE TITLE
Possible to use generics for return types of List?

### ISSUE THREAD

**Issue by vennekilde** [mulesoft-labs/raml-for-jax-rs#388]
Hi

I was wondering if it would be possible to use generics for the class type when generating lists

Example
```
#%RAML 1.0
title: Example
version: v1
baseUri: http://localhost:8080
protocols:
  - HTTPS
types:
    t1:
        properties:
            elements:
                type: e1[]
    t2:
        type: t1
        properties:
            elements:
                type: e2[]
    e1:
        type: object
        properties:
            p1:
                type: string
    e2:
        type: e1
        properties:
            p2:
                type: string
```
Will not be able to compile due to (along with some more, but identical errors)
`example.model.T2Impl cannot implement getElements() in example.model.T1 return type java.util.List<example.model.E2> is not compatible with java.util.List<example.model.E1>`

The problem is that when the methods are generated, they use `List<E1>` instead of `List<? extends E1>`

**Comment by jpbelang** [comment]
That's interesting.  I'll check to see if this is fixable entirely(for real) or by plugin(quick workaround).  On the weekend.

**Comment by jpbelang** [comment]
```yaml
    listElementParent:
      type: object
      properties:
        name: string

    listElementChild:
      type: listElementParent
      properties:
        name: string

    listHolderParent:
      type: object
      (ramltopojo.types):
        plugins:
          - name: core.wildcardcollection
            arguments: [java.lang.Object]
      properties:
        elements: listElementParent[]
        names: string[]
        id: integer

    listHolderChild:
      type: listHolderParent
      properties:
        elements: listElementChild[]
```
I've done it as a plugin because I have to remove the setters (maybe I'm paranoid), and allows you to fool around with the types.  If you don't set the class parameter, it goes to the default parent type.
