### ISSUE TITLE
Generated java of subtypes won't compile

### ISSUE THREAD

**Issue by vromero** [mulesoft-labs/raml-for-jax-rs#402]
When using a RAML that has for instance a response envelope:

myEnvelope that has some members in it, when creating a subtype, eg: EnvelopeForParticularResource it will generate enums and other types again, creating a change in the Java signature and therefore not compiling for the subtype.

See the following example project to reproduce 
[raml-defined-example.tar.gz](https://github.com/mulesoft-labs/raml-for-jax-rs/files/3204496/raml-defined-example.tar.gz).

As a dirty workaround I've been able to change the type: mylib.myType for an type: !include ... which does the trick but is a far cry from ideal.

**Comment by jpbelang** [comment]
I'll look into it on the weekend.  Thanks for the example.

**Comment by jpbelang** [comment]
Ah, yes.  Inline types.  The gift that keeps on giving :-)

Your current spec contains what is, for all intents and purposes this file (api-standards):
```yaml
types:
  response-envelope:
    type:
      properties:
        status:
          type: string
          enum: [Success, Failure]
          required: true
        error:
          description: Error information for failed requests.
          type: object
          required: false
          properties:
            message:
              type: string
              required: true
              example: Success
            reason:
              type: string
              required: true
            details:
              type: string
              required: false
    properties:
      metadata:
        type: object
        required: false
        properties:
          offset:
            type: integer
          limit:
            type: integer
          resultCount:
            type: integer
          totalCount:
            type: integer
      data:
        description:
        type: any
        required: false
```

which means that the properties in the _inline_ parent type of `response-envelope`.  When I go through the properties of a type, I
try to figure out if the property is an inline type.  In this case, both the `status` and `error` properties register as new inline types
in both `ResponseEnveloppe` and `SalutationsEnveloppe`, so I generate two types.  These types have no relationship, so java can't apply
its covariant return type rules (as the return type from `status` in `ResponseEnveloppe` has no relationship with `status` in `SalutationEnveloppe`)

All of this comes from the problem that there is no way, in the current parser, to figure out what is an inline type, which makes
the whole thing rather error prone.

I also can't do inheritance from inline types, I think.  This would sort of double all the problems that inline types cause.


This almost works.  We'll get to the last issue in a second.

```yaml
#%RAML 1.0 Library

types:
  Status:
    type: string
    enum: [Success, Failure]
    required: true
  Error:
    description: Error information for failed requests.
    type: object
    required: false
    properties:
      message:
        type: string
        required: true
      reason:
        type: string
        required: true
      details:
        type: string
        required: false
  MetaData:
    type: object
    required: false
    properties:
      offset:
        type: integer
      limit:
        type: integer
      resultCount:
        type: integer
      totalCount:
        type: integer

  StatusHolder:
    properties:
      status: Status
      error: Error

  response-envelope:
    type: StatusHolder
    properties:
      metadata: MetaData
      data:
        type: any
        required: false

```

The last issue has to do with the `any` type being overridden here:

```yaml
  data:
    description: 
    type: any
    required: false
```

any maps to java `Object`.  All of this works until you try to override it.  Java has covariant return types, 
but no covariant parameters.  This means that when you override a type, getters will be properly overridden, but setters will 
not be handled properly. The only way to fix this is to have all inherited properties that descent from an `any` type to never
actually expose anything but Object in the setter type so that the getter would be properly typed, but not the setter.  The field 
would have the proper type but then be subject to some form of runtime error. 

This I'd rather do through some form of plugin.
