### ISSUE TITLE
hi, this group not active?

### ISSUE THREAD

**Issue by rkrgarlapati** [mulesoft-labs/raml-for-jax-rs#434]
Hi

**Comment by jpbelang** [comment]
Not exaclty sure what version you were using.
```yaml
            versions:
              type: array
              items:
                properties:
                  key:
                    type: string
                    required: false
```
This is handled by the raml-java-tools project.  There are examples that seem to work with your case. specifically 
```yaml
    inlineStuff:
      type: array
      items:
         type: object
         properties:
             last: string
```
The difference may be the "type: object" line.  

The underlying parser that was used in 3.x.x is very finicky about inline types (sometimes having them behave differently...).  
Examples are in this project:
https://github.com/mulesoft-labs/raml-java-tools
Around here:
`raml-to-pojo-maven-example/src/main/resources/arrays.raml`

**Comment by jpbelang** [comment]
Which version are you using ?

**Comment by rkrgarlapati** [comment]
`#%RAML 1.0`

**Comment by rkrgarlapati** [comment]
Strange issue:

As you suggested i used this plugin,
```
<plugin>
	<groupId>org.raml</groupId>
	<artifactId>raml-to-pojo-maven-plugin</artifactId>
	<version>1.0.6</version>
	<executions>
		<execution>
			<id>goo</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<defaultPackage>foo.foo</defaultPackage>
				<ramlFile>
					c:\raml-path\process-api.raml
				</ramlFile>

				<!--<basePlugins>
					<value>core.equalsAndHashCode</value>
				</basePlugins>-->
				<resourcePackage>com.folder.client.resources</resourcePackage>
				<modelPackage>com.folder.client.model</modelPackage>
				<supportPackage>com.folder.client.support</supportPackage>
				<outputDirectory>${project.basedir}/src/main/java</outputDirectory>

			</configuration>
		</execution>
	</executions>
</plugin>
```
compile successful, generated stubs only for 'uses' section, but skipped for the entire body of RAML, didn't generate any stubs for my endpoints.
for example, this plugin generated stubs only for this section, skipped the body part:
```
uses:
  Health: /health-check/health-check.raml
  StandardErrors: /errors-library/errors-library.raml
```	

With the same raml, i used raml-to-jaxrs-maven-plugin, it successfully generated stubs, but only trick is i need to use (ramltopojo.types) annotation as mentioned in my original post.

**Comment by jpbelang** [comment]
Ok, cool.  

The raml to pojo plugin only generates types defined in the raml files.  It handles the types, whether they be inline or straight up standalone types.

The raml-to-jaxrs plugin generates the endpoints and calls the raml-to-pojo code when it finds an inline type defined in its endpoints (except for jsonschema types and xmlschema types, which you are not using).

So errors when generating types (like the one you were (are) getting with arrays) are the responsibility of raml-to-pojo.  The thing I'm not understanding is why in my examples (in the raml-to-pojo project) the generation works (without the annotation) 

There is another piece of software that I'm relying on called the raml-java-parser.  This parser is being deprecated and has many issues (relative to inline types): one of them is it handles inline arrays in unpredictable ways (sometimes it calls the items objects, sometimes their proper type...).  It's very annoying.  It's what is happening around your type.  However, from trying to understand what you are trying to do, I seem to have examples that work at generating the code properly.  It's just that your raml has issues that trigger the parser problem.

So this is a bit of a shot in the dark, but change:
```yaml
            versions:
              type: array
              items:
                properties:
                  key:
                    type: string
                    required: false
```

to:
```yaml
```yaml
            versions:
              type: array
              items:
                type: object  # <------- this
                properties:
                  key:
                    type: string
                    required: false
```
And run the raml-for-jaxrs stuff again (and remove the annotation).

**Comment by rkrgarlapati** [comment]
same error:
```
Error generating Java classes from: null
: unable to create type array item of type object (or maybe an inline array type ?) -> [Help 1]
```
Not Working:
```
myname:
  type: string
  required: false   
  description: Nick Name
  example: "Activate fellow" 
versions:
  type: array
  items:
    type: object
    properties:
	  key:
	    type: string
	    required: false
	    example: myownOS                    
	  value:
	    type: string
	    required: false
	    example: "2.2"
```
		
with annotation, it's working:
```
myname:
  type: string
  required: false   
  description: Nick Name
  example: "Activate fellow" 
versions:
  (ramltopojo.types):
    generateInlineArrayType: true
  type: array
  items:
    type: object
    properties:
	  key:
	    type: string
	    required: false
	    example: myownOS                    
	  value:
	    type: string
	    required: false
	    example: "2.2"	
```

pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.company.project</groupId>
    <artifactId>Simulator</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.raml.jaxrs</groupId>
                <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
                <version>3.0.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.raml.jaxrs</groupId>
                        <artifactId>feature-plugins</artifactId>
                        <version>3.0.5</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <ramlFile>${project.basedir}\src\main\resources\api.raml
                    </ramlFile>
                    <resourcePackage>com.project.company.resources</resourcePackage>
                    <modelPackage>com.project.company.model</modelPackage>
                    <supportPackage>com.project.company.support</supportPackage>
                    <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                    <jsonMapper>jackson2</jsonMapper>
                    <generateTypesWith>jsr303</generateTypesWith>
                    <jsonMapperConfiguration>
                        <includeAdditionalProperties>false</includeAdditionalProperties>
                    </jsonMapperConfiguration>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```
