### ISSUE TITLE
jax-rs->raml : Is it possible to use global security scheme

### ISSUE THREAD

**Issue by Kindrat** [mulesoft-labs/raml-for-jax-rs#50]
It is possible to use global security with maven plugin?

```
#%RAML 0.8
title: API Documentation
baseUri: http://localhost:8080
version: v1
securedBy: [basic]
securitySchemes:
   - basic:
        type: Basic Authentication
```
